<?php
/**
 * Created by PhpStorm.
 * User: longbob
 * Date: 2020-02-17
 * Time: 18:41
 */

namespace Optimize\Command;


use Optimize\Conf\RuleConf;
use Optimize\Lib\CodeParser;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MainCommand extends ScanCommand
{
    protected static $defaultName = 'scan:for';

    public function execute(InputInterface $input, OutputInterface $output)
    {
        CodeParser::setRules(RuleConf::$data['forOrForeach']);
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}